// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0CJGYL98Ko8bRClyhlezpRiTXKOSu_Bk',
    appId: '1:595311666355:web:74a41196bd6998c818fcc6',
    messagingSenderId: '595311666355',
    projectId: 'shgumed-d3027',
    authDomain: 'shgumed-d3027.firebaseapp.com',
    storageBucket: 'shgumed-d3027.appspot.com',
    measurementId: 'G-RNLTEB8QYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFkhA3FAoiN2ZdCYLXixvBSRhseHh6dlc',
    appId: '1:595311666355:android:232c7e83032996f018fcc6',
    messagingSenderId: '595311666355',
    projectId: 'shgumed-d3027',
    storageBucket: 'shgumed-d3027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnfskUV2QtPHPpE43fWVO3jF-c2egll0',
    appId: '1:595311666355:ios:06e44a85e7bd4d7218fcc6',
    messagingSenderId: '595311666355',
    projectId: 'shgumed-d3027',
    storageBucket: 'shgumed-d3027.appspot.com',
    iosBundleId: 'com.example.finalPro',
  );
}
